name: Deploy to EC2

on:
  push:
    branches: [main]

jobs:
  deploy:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Pre-deploy check
        run: |
          if [ -f "/home/ubuntu/pre-deploy.sh" ]; then
            bash /home/ubuntu/pre-deploy.sh
          fi

      - name: Deploy to EC2
        uses: appleboy/ssh-action@v0.1.6
        with:
          host: ${{ secrets.EC2_HOST }}
          username: ${{ secrets.EC2_USER }}
          key: ${{ secrets.SSH_PRIVATE_KEY }}
          script: |
            cd /home/ubuntu/your-app-directory
            git pull origin main
            npm install --production
            pm2 restart your-app-name
            echo "Deployment completed successfully!"